export { default as AboutContent } from './AboutContent';
export { default as Footer } from './Footer';
export { default as Form } from './Form';
export { default as HeroImg } from './HeroImg';
export { default as HeroImg2 } from './HeroImg2';
export { default as Navbar } from './Navbar';
export { default as Work } from './Work';
export { default as WorkCard } from './WorkCard';
export { default as PricingCard } from './PricingCard';
