import { image } from '../theme';

const CardData = [
  {
    title: 'React',
    image: image.react,
    shadowColor: '#61dafb ',
    url: 'https://reactjs.org',
    proficiency: 700,
  },
  {
    title: 'React-Native',
    image: image.react,
    shadowColor: '#61dafb ',
    url: 'https://reactnative.dev',
    proficiency: 1000,
  },
  {
    title: 'TypeScript',
    image: image.typescript,
    shadowColor: '#3178C6',
    url: 'https://www.typescriptlang.org',
    proficiency: 820,
  },
  {
    title: 'Expo',
    image: image.expo,
    shadowColor: '#FFFFFF',
    url: 'https://expo.dev',
    proficiency: 0,
  },
  {
    title: 'Redux',
    image: image.redux,
    shadowColor: '#764ABC',
    url: 'https://redux.js.org',
    proficiency: 720,
  },
  {
    title: 'redux-thunk',
    image: image.redux,
    shadowColor: '#764ABC',
    url: 'https://redux.js.org',
    proficiency: 620,
  },
  {
    title: 'redux-query',
    image: image.react_query,
    shadowColor: '#FFFFFF',
    url: 'https://redux-toolkit.js.org/rtk-query/overview',
    proficiency: 620,
  },
  {
    title: 'Emotion',
    image: image.emotion,
    shadowColor: '#D36AC2',
    url: 'https://emotion.sh/docs/introduction',
    proficiency: 0,
  },
  {
    title: 'JavaScript',
    image: image.javascript,
    shadowColor: '#FFD83A',
    url: 'https://developer.mozilla.org/ko/docs/Web/JavaScript',
    proficiency: 600,
  },
  {
    title: 'Github',
    image: image.github,
    shadowColor: '#ffffff',
    url: 'https://github.com/jwAndroid',
    proficiency: 0,
  },
  {
    title: 'Firebase',
    image: image.firebase,
    shadowColor: '#FCCA3F',
    url: 'https://firebase.google.com',
    proficiency: 0,
  },
  {
    title: 'Eslint',
    image: image.eslint,
    shadowColor: '#4B32C3',
    url: 'https://eslint.org',
    proficiency: 0,
  },
  {
    title: 'Android',
    image: image.android,
    shadowColor: '#82BC01',
    url: 'https://developer.android.com',
    proficiency: 750,
  },
  {
    title: 'Java',
    image: image.java,
    shadowColor: '#E11F21',
    url: 'https://www.java.com',
    proficiency: 400,
  },
  {
    title: 'Kotlin',
    image: image.kotlin,
    shadowColor: '#8168FF',
    url: 'https://kotlinlang.org',
    proficiency: 550,
  },
  {
    title: 'Dart',
    image: image.dart,
    shadowColor: '#03589C',
    url: 'https://dart.dev/',
    proficiency: 100,
  },
  {
    title: 'ReactiveX',
    image: image.rx,
    shadowColor: '#FF0088',
    url: 'https://reactivex.io/',
    proficiency: 200,
  },
];

export default CardData;
