import { image } from '../theme';

export const ProjectData = [
  {
    src: image.chatmo,
    title: 'ChatMo',
    text: '채팅형식 메모장 앱으로 사용하는데 필수적인 기능들을 구현한 앱 입니다.',
    github: 'https://github.com/jwAndroid/ChatMo.v2',
    route: 'chatmo',
    stack: ['react-native', 'published'],
    content: 'chatmo 컨텐츠 입니다.',
    video: 'chatmo url',
  },
  {
    src: image.wetrip,
    title: 'Wetrip',
    text: '(주)트립메이트 에서 제공하는 여행관련 동행모집 플랫폼 서비스 입니다.',
    github: '',
    route: 'wetrip',
    stack: ['react-native', 'published'],
    content: 'wetrip 컨텐츠 입니다.',
    video: 'wetrip url',
  },
  {
    src: image.expo_background,
    title: 'Expo',
    text: 'React Native 와 Expo 환경에서의 개발을 공부한 내용입니다.',
    github: 'https://github.com/jwAndroid/expo-rn',
    route: 'expo',
    stack: ['react-native'],
    content: 'Expo 컨텐츠 입니다.',
    video: 'Expo url',
  },
  {
    src: image.covid,
    title: 'Covid-19 Board',
    text: '각 지역별로 코로나 확진자 파악, 주변 병원 검색 기능이 담겨져 있는 앱 입니다.',
    github: 'https://github.com/jwAndroid/Covid19_SB',
    route: 'covid',
    stack: ['Android'],
    content: 'covid 컨텐츠 입니다.',
    video: 'covid url',
  },
  {
    src: image.friending,
    title: 'Friending',
    text: '사진공유, 채팅, 좋아요기능 등 일반적인 SNS 서비스 입니다.',
    github: 'https://github.com/jwAndroid/Friending',
    route: 'friending',
    stack: ['Android'],
    content: 'friending 컨텐츠 입니다.',
    video: 'https://www.youtube.com/watch?v=TBmoY7VScXw',
  },
  {
    src: image.noteapp,
    title: 'Note',
    text: '스티커 형식의 메모장 앱 입니다.',
    github: 'https://github.com/jwAndroid/Noteapp',
    route: 'noteapp',
    stack: ['Android'],
    content: 'noteapp 컨텐츠 입니다.',
    video: 'expo url',
  },
  {
    src: image.todoapp,
    title: 'Todo',
    text: 'Todo 체크리스트 앱 입니다.',
    github: 'https://github.com/jwAndroid/TodoList',
    route: 'todoapp',
    stack: ['Android'],
    content: 'todoapp 컨텐츠 입니다.',
    video: 'todoapp url',
  },
  {
    src: image.coffee,
    title: 'CoffeeDream',
    text: '매장홍보를 위한 카페홍보용 앱 입니다.',
    github: 'https://github.com/jwAndroid/CoffeeDream',
    route: 'coffee',
    stack: ['Android'],
    content: 'coffee 컨텐츠 입니다.',
    video: 'coffee url',
  },
];

export default ProjectData;
