import { image } from '../theme';

export const ProjectData = [
  {
    src: image.chatmo,
    title: 'ChatMo',
    text: '채팅형식 메모장 앱으로 사용하는데 필수적인 기능들을 구현한 앱 입니다.',
    github: 'https://github.com/jwAndroid/ChatMo.v2',
    route: 'chatmo',
    stack: ['react-native', 'published'],
    content: {
      text: '처음으로 해본 ~~~ 챗모앱~~~~ 오늘 배포되었찌~~',
      devYear: '2011~2012',
      published: true,
      publishedUrl: 'https://www.apple.com/kr/app-store',
      isCompany: false,
      createdAt: '2022-10-12',
      videoUrl: 'https://www.youtube.com/watch?v=Uigw-spcSD4',
    },
  },
  {
    src: image.wetrip,
    title: 'Wetrip',
    text: '(주)트립메이트 에서 제공하는 여행관련 동행모집 플랫폼 서비스 입니다.',
    github: '',
    route: 'wetrip',
    stack: ['react-native', 'published'],
    content: {
      text: '처음으로 해본 ~~~ 챗모앱~~~~ 오늘 배포되었찌~~',
      devYear: '2011~2012',
      published: true,
      publishedUrl: 'https://www.apple.com/kr/app-store',
      isCompany: false,
      createdAt: '2022-10-12',
      videoUrl: 'https://www.youtube.com/watch?v=Uigw-spcSD4',
    },
  },
  {
    src: image.expo_background,
    title: 'Expo',
    text: 'React Native 와 Expo 환경에서의 개발을 공부한 내용입니다.',
    github: 'https://github.com/jwAndroid/expo-rn',
    route: 'expo',
    stack: ['react-native'],
    content: {
      text: 'react-native expo 환경 에서의 장점을 활용하여 여러 기능들을 테스트 및 공부 해보았습니다. \n기본적인 기능부터 복잡하고 앱 구현에 있어서 핵심적인 기능까지 다양한 테스트를 해보았습니다. \nExpo 로 현재 출시된 앱은 ChatMo 라는 채팅형 메모 앱과 Wetrip "(c) tripmate" 이라는 여행 동행 앱을 QA,개발하고 배포 했습니다.',
      devYear: '2011~2012',
      published: true,
      publishedUrl: 'https://www.apple.com/kr/app-store',
      isCompany: false,
      createdAt: '2022-10-12',
      videoUrl: 'https://www.youtube.com/watch?v=ITX8NmQaW6Q',
    },
  },
  {
    src: image.covid,
    title: 'Covid-19 Board',
    text: '각 지역별로 코로나 확진자 파악, 주변 병원 검색 기능이 담겨져 있는 앱 입니다.',
    github: 'https://github.com/jwAndroid/Covid19_SB',
    route: 'covid',
    stack: ['Android'],
    content: {
      text: '처음으로 해본 ~~~ 챗모앱~~~~ 오늘 배포되었찌~~',
      devYear: '2011~2012',
      published: true,
      publishedUrl: 'https://www.apple.com/kr/app-store',
      isCompany: false,
      createdAt: '2022-10-12',
      videoUrl: 'https://www.youtube.com/watch?v=Uigw-spcSD4',
    },
  },
  {
    src: image.friending,
    title: 'Friending',
    text: '사진공유, 채팅, 좋아요기능 등 일반적인 SNS 서비스 입니다.',
    github: 'https://github.com/jwAndroid/Friending',
    route: 'friending',
    stack: ['Android'],
    content: {
      text: '처음으로 해본 ~~~ 챗모앱~~~~ 오늘 배포되었찌~~',
      devYear: '2011~2012',
      published: true,
      publishedUrl: 'https://www.apple.com/kr/app-store',
      isCompany: false,
      createdAt: '2022-10-12',
      videoUrl: 'https://www.youtube.com/watch?v=Uigw-spcSD4',
    },
  },
  {
    src: image.noteapp,
    title: 'Note',
    text: '스티커 형식의 메모장 앱 입니다.',
    github: 'https://github.com/jwAndroid/Noteapp',
    route: 'noteapp',
    stack: ['Android'],
    content: {
      text: '처음으로 해본 ~~~ 챗모앱~~~~ 오늘 배포되었찌~~',
      devYear: '2011~2012',
      published: true,
      publishedUrl: 'https://www.apple.com/kr/app-store',
      isCompany: false,
      createdAt: '2022-10-12',
      videoUrl: 'https://www.youtube.com/watch?v=Uigw-spcSD4',
    },
  },
  {
    src: image.todoapp,
    title: 'Todo',
    text: 'Todo 체크리스트 앱 입니다.',
    github: 'https://github.com/jwAndroid/TodoList',
    route: 'todoapp',
    stack: ['Android'],
    content: {
      text: '처음으로 해본 ~~~ 챗모앱~~~~ 오늘 배포되었찌~~',
      devYear: '2011~2012',
      published: true,
      publishedUrl: 'https://www.apple.com/kr/app-store',
      isCompany: false,
      createdAt: '2022-10-12',
      videoUrl: 'https://www.youtube.com/watch?v=Uigw-spcSD4',
    },
  },
  {
    src: image.coffee,
    title: 'CoffeeDream',
    text: '매장홍보를 위한 카페홍보용 앱 입니다.',
    github: 'https://github.com/jwAndroid/CoffeeDream',
    route: 'coffee',
    stack: ['Android'],
    content: {
      text: '처음으로 해본 ~~~ 챗모앱~~~~ 오늘 배포되었찌~~',
      devYear: '2011~2012',
      published: true,
      publishedUrl: 'https://www.apple.com/kr/app-store',
      isCompany: false,
      createdAt: '2022-10-12',
      videoUrl: 'https://www.youtube.com/watch?v=Uigw-spcSD4',
    },
  },
];

export default ProjectData;
